version: '3.4'
services:
  add:
    build:
      context: app-adder
      dockerfile: Dockerfile
    image: fearlesstech/k8straining_add:latest
    tty: true
    container_name: add
    ports: 
      - "5678:80"
    environment: 
      - PORT=80
    networks:
      - nginx_nw
      - add_mult
  multiply:
    build:
      context: app-multiplier
      dockerfile: Dockerfile
    image: fearlesstech/k8straining_multiply:latest
    tty: true
    container_name: multiply
    ports: 
      - "6789:80"
    environment: 
      - PORT=80
      - ADDENDPOINT=http://add/add
    networks:
      - nginx_nw
      - add_mult
  nest1:
    build:
      context: app-nest1
      dockerfile: Dockerfile
    image: fearlesstech/k8straining_nest1:latest
    tty: true
    container_name: nest1
    ports: 
      - "7896:80"
    environment: 
      - PORT=80
      - NEST2ENDPOINT=http://nest2/nest2
    networks:
      - nginx_nw
      - nest_nw
  nest2:
    build:
      context: app-nest2
      dockerfile: Dockerfile
    image: fearlesstech/k8straining_nest2:latest
    tty: true
    container_name: nest2
    ports: 
      - "8765:80"
    environment: 
      - PORT=80
      - WHATTOSAY=banana
    networks:
      - nest_nw
  router:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./router/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - nginx_nw
networks: 
  nginx_nw:
    driver: bridge
  add_mult: 
    driver: bridge
  nest_nw:
    driver: bridge
