version: '3.4'
services:
  add:
    build:
      context: adder
      dockerfile: Dockerfile
    tty: true
    container_name: add
    ports: 
      - "5678:3000"
    environment: 
      - PORT=3000
    networks:
      - add_nw
  multiply:
    build:
      context: multiplier
      dockerfile: Dockerfile
    tty: true
    container_name: multiply
    ports: 
      - "6789:4000"
    environment: 
      - PORT=4000
      - ADDENDPOINT=add/add
    networks:
      - multiply_nw
      - add_nw
  router:
    image: nginx:latest
    ports:
      - "9696:80"
    volumes:
      - "./router/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - nginx_nw
      - add_nw
      - multiply_nw
networks: 
  nginx_nw:
    driver: bridge
  add_nw: 
    driver: bridge
  multiply_nw: 
    driver: bridge