version: '3.4'
services:
  add:
    build:
      context: adder
      dockerfile: Dockerfile
    tty: true
    container_name: add
    ports: 
      - "5678:3000"
    environment: 
      - PORT=3000
    networks:
      - add_nw
  multiply:
    build:
      context: multiplier
      dockerfile: Dockerfile
    tty: true
    container_name: multiply
    ports: 
      - "6789:4000"
    environment: 
      - PORT=4000
      - ADDENDPOINT=add/add
    networks:
      - multiply_nw
networks: 
  add_nw: 
    driver: bridge
  multiply_nw: 
    driver: bridge